### ISSUE TITLE
Code for specific access settings

### ISSUE THREAD

**Issue by SimonParkerDKFZ** [EBISPOT/DUO#110]
As mentioned at the DUO workshop, I am interested if data depositors can specify where the data is accessed.

For example, some health data providers may prefer that the data is accessed only within an institutional setting or within a restricted access Trusted Research Environment.

This could potentially extend to access only within an ISO 27001 approved setting or similar national level accreditations (such DSPT in England and Wales)

**Comment by mcourtot** [comment]
Discussed at DUO call on May 19th 2021: This term is not in scope for DUO and we have talked to the Data Access Committee Review Standard (DACReS) group which will handle it; eventually the DACReS/REWS will have guidance for data access we can point to.
cc @solideoglori
