### ISSUE TITLE
Potential implementation

### ISSUE THREAD

**Issue by annaasklof** [EBISPOT/DUO#122]
We just want to make you aware of a potential implementation of the data use ontology that we are working. We are interested in adopting the DUO codes in the work we do on data access statements at SciLifeLab. SciLifeLab, Science for Life Laboratory, is a national research infrastructure funded by the Swedish government. When working on data access statements we came across the data use ontology and thought it might be of use to us. We have an instance of Figshare (https://scilifelab.figshare.com/) and as a first step we are working with data access statements for this instance.

https://github.com/ScilifelabDataCentre/SciLifeLab-Data-Repository-DAS

**Comment by mcourtot** [comment]
That's great, thanks for the note @annaasklof! Let us know if we can be of any help.
