### ISSUE TITLE
Suggested additions: minimum size of the dataset, Quality control criteria, Board requirements

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/DUO#15]
Comment from Peter Rogan on [ga4gh-data-use-subgroup mailing-list](https://groups.google.com/a/ga4gh.org/forum/#!topic/ga4gh-data-use-subgroup/CnKDGO2hlc4)

I would like to suggest that you add elements to the matching algorithm of the ontology which should be helpful for both researchers and those restricting use of the data. These would contribute to ensuring eligibility and usefulness of the datasets

The minimum size of the dataset (in samples)
Quality control criteria (this could be a binary Y/N, categorical (statistical, replicates, etc), or descriptive
Any Research Ethics Board or Institutional Review Board requirements (if any)

**Comment by nmcabili** [comment]
Dear Peter,

Thank you for your comments! These are indeed critical to enabling a discovery query. 
I believe the place of the of items #1 and #2 is as part of the GA4GH data Discovery API and data model.
As for comment #3 : the data use code IRB taken from Consent Codes address exactly your request http://purl.obolibrary.org/obo/DUO_0000021 .

Many thanks!
Moran Cabili
Broad Institute
GA4GH DURI co-chair

**Comment by mcourtot** [comment]
Hi Peter - I am porting the other 2 terms to the schema blocks repository which is where the general data model lives. Please see https://github.com/ga4gh-schemablocks/blocks/issues/2 and follow up there.
