### ISSUE TITLE
Is there an example of an existing consent that has been tagged with DUO?

### ISSUE THREAD

**Issue by leipzig** [EBISPOT/DUO#17]

**Comment by mcourtot** [comment]
Hi Jeremy - have a look at https://ega-archive.org/datasets/EGAD00001000002 to see an example of dataset currently tagged with DUO. 

If you are asking for "how to translate data use letters into DUO codes" there is no extensive guide about this yet, though we are planning on producing some of worked use cases. The closest atm would be the readme at https://github.com/EBISPOT/DUO#examples-of-use

If you have specific examples in mind we could make sure to add those in the doc, or if you're referring to something else please let me know!

**Comment by leipzig** [comment]
Yes, that's very helpful. Thank you.
