### ISSUE TITLE
Publish a minimal version of DUO for implementation

### ISSUE THREAD

**Issue by kreinold** [EBISPOT/DUO#18]
Implementers would like to limit the import of DUO to the terms needed for implementation.  I've used ontofox, based on MIREOT principles to create subsets of several ontologies with simply rdfs:label, id, and subclass/superclass relationships with great success.

**Comment by mcourtot** [comment]
See https://github.com/EBISPOT/DUO/blob/master/src/ontology/duo-basic.owl
If the group agrees this is what we'll load on OLS (with an option to get the full version if desired)

CSV version at https://github.com/EBISPOT/DUO/blob/master/src/ontology/duo.csv

**Comment by mcourtot** [comment]
from @kreinold :   I've tested with the basic version of the ontology; looks good.
