### ISSUE TITLE
make distributable release that does not include BFO

### ISSUE THREAD

**Issue by mellybelly** [EBISPOT/DUO#20]
It is difficult for a naive user (or even an advanced one) to use DUO with all the BFO content in there. no need, it can be in a bridge file.

**Comment by mcourtot** [comment]
Totally agreed and is in the works :) We've discussed with @simonjupp and @kreinold and will make a "core" release at the next iteration.
Relates to https://github.com/EBISPOT/DUO/issues/18 and https://github.com/EBISPOT/DUO/issues/14

**Comment by mcourtot** [comment]
See https://github.com/EBISPOT/DUO/blob/master/src/ontology/duo-basic.owl
If the group agrees this is what we'll load on OLS (with an option to get the full version if desired)

**Comment by mcourtot** [comment]
@kreinold tested the basic version which works well. Group was happy with it at last call too.
