### ISSUE TITLE
make consistent contributors

### ISSUE THREAD

**Issue by mellybelly** [EBISPOT/DUO#21]
in OBO metadata and on https://github.com/EBISPOT/DUO#duo-logos

Might be good to have some criteria for inclusion- tickets? comments? PRs? etc.

**Comment by mcourtot** [comment]
We have asked people to self nominate via PR to the readme list of contributors. Threshold is low - if they feel they contributed to the resource they should add their name.

**Comment by mcourtot** [comment]
On the DU call on [June 5th](https://docs.google.com/document/d/151UEa4tD0BTP91k_krpPPb3mzxX-4MCFxuz-IeX3s00/edit#heading=h.oippy5eym2hg) attendees were reminded to add themselves to the contributors list
