### ISSUE TITLE
Reference to owl-basic in obo in invalid

### ISSUE THREAD

**Issue by kreinold** [EBISPOT/DUO#26]
http://purl.obolibrary.org/obo/duo-basic.owl takes us to an amazon bucket description rather than the xml/rdf.

**Comment by mcourtot** [comment]
Yes this is expected until release at which time I will create the PURL redirection. Thanks for the feedback!

**Comment by kreinold** [comment]
Thanks for the quick response!!
  Kathy
*Kathy Reinold*
*Principal Data Modeler, Data Sciences Platform *
The Broad Institute of Harvard and MIT
105 Broadway - 359M
Cambridge, MA 02142

**Comment by mcourtot** [comment]
http://purl.obolibrary.org/obo/duo/releases/2020-02-03/duo-basic.owl

This has been fixed with the 2020-02-03 relesase.
