### ISSUE TITLE
duo-basic missing object property 'is restricted to'

### ISSUE THREAD

**Issue by kreinold** [EBISPOT/DUO#27]
Was this intentional?

**Comment by kreinold** [comment]
And can you provide a more specific example of its use?  I'm not completely sure I understand.

**Comment by mcourtot** [comment]
Well spotted @kreinold! duo-basic was meant to include only the DUO classes, so no properties (annotation or object) are included indeed.

Now looking at 'is restricted to' I think we should deprecate it. I'll create a separate ticket for this.
