### ISSUE TITLE
Propose to change the DUO:0000025's definition to a specified date (should be a minor update)

### ISSUE THREAD

**Issue by haoyuanli** [EBISPOT/DUO#31]
Having thought about the implementation for a bit, I realized that shorthand isn't the biggest problem, as implementation relies on the id as the unique identifier. The -[XX] part is fine, it can be interpreted as that this code needs an accompanying comment, but removing that makes the code look cleaner

It looks like it does make implementation easier tho, if `DUO:0000025`, the `time limit on use`, specifies the 'end date' instead of `number of months`. I know the upcoming changes will possibly make this field to be of certain datetime format, but even if the schema doesn't define that, we can still enforce a YYYY-MM-DD date time format during the implementation, provided that the definition also says an `end date`. 

Right now it's hard to implement this code because we can't serve back a date time when the schema says `number of months`. I am however able to enforce a YYYY-MM-DD datetime validation for DUO:0000024	MOR-[XX], even if the schema hasn't defined the datetime format yet.

Btw, do DUO:0000007 DS DUO:0000028 IS also need modifier?

**Comment by mcourtot** [comment]
Thanks for the feedback - you're totally right re DUO:0000025, see https://github.com/EBISPOT/DUO/issues/10

DUO:0000007 is meant to work for a term from a disease ontology, we are working with the MONDO team to formalise a recommendation. 

I don't think there will be a modifier for DUO:0000028 at the moment: in our use cases this is understood as being "the institution that signed the agreement" by the DACs. However, one could add a modifier perhaps from GRID, https://www.grid.ac?

**Comment by haoyuanli** [comment]
Cool, ok, thanks

Question for DUO:0000018

The definition says "This requirement indicates that use of the data is limited to not-for-profit organizations and not-for-profit use, non-commercial use."

My understanding is that the entity has to satisfy both conditions here
- `not-for-profit organizations` AND
- `not-for-profit use, non-commercial use.`
