### ISSUE TITLE
are DUO_0000031 to DUO_0000040 ob·so·lete

### ISSUE THREAD

**Issue by haoyuanli** [EBISPOT/DUO#32]
They seem to use underscore whereas other use `:`

![image](https://user-images.githubusercontent.com/18109953/69677409-bd28fa80-1057-11ea-9c98-607a30e11081.png)

**Comment by mcourtot** [comment]
HI @haoyuanli  - those "ids" are just annotation properties with no logical values. The OWL reads:
`  <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">DUO_0000031</oboInOwl:id>`
I guess an error was made when they were inserted in that they used an underscore, but this doesn't change the ID of the term nor its validity. The IRI of this term would be http://purl.obolibrary.org/obo/DUO_0000031

I will do the update of the IDs nonetheless as we use those APs to build the csv version and we may include those terms in it in the future. Also for consistency. Thanks for the report!

**Comment by haoyuanli** [comment]
yeah it would be good for consistency, it'd be a bit confusing if some of the IDs use underscore some of the IDs use colon
