### ISSUE TITLE
DUO:0000001 - DUO:0000003 do not have a shorthand

### ISSUE THREAD

**Issue by haoyuanli** [EBISPOT/DUO#34]
I guess the shorthand is optional, so this could be optional, since ID is the only unique identifier here.

These 3 being the only codes that don't have a shorthand, i suppose we could do something like

```
DUO code             name                                proposed shorthand
DUO:0000001          consent code                        CC
DUO:0000002          consent code primary category       CCP (or CC1)
DUO:0000003          consent code secondary category     CCS (or CC2)
```

Of course, this doesn't really change anything fundamental haha..

Plus i can sort of guess why theres no shorthand for these 3 as they seem to be the general 'parent' terms that encapsulate all others

**Comment by mcourtot** [comment]
Fair point. Note that we have agreed to deprecate those terms, so won't be adding any shorthand.
