### ISSUE TITLE
Label change: data use limitation

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/DUO#44]
The DUO group should decide which label is preferred amongst data use limitation, data use categories, data use permission. Others are to be added as alternative terms.

**Comment by mcourtot** [comment]
Adrian suggests data use condition

**Comment by mcourtot** [comment]
@kreinold limitations -> restrictions and obligations

**Comment by solideoglori** [comment]
![image](https://user-images.githubusercontent.com/52168754/80593876-f3e0b380-89ef-11ea-9c5a-98356add0a73.png)

Here is an example of how we have been thinking through it internally at the Broad

**Comment by solideoglori** [comment]
Addressed by #94

**Comment by mcourtot** [comment]
I am going to close this one to prevent confusion and as it is handled by #94
