### ISSUE TITLE
Publish governance process on GH

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/DUO#50]
https://docs.google.com/document/d/14Mxochx9zzYNA7jWi2jhQBzsAFYoSWDWTjjB49eYSvs/edit#heading=h.ce3ivxkbokk5

**Comment by solideoglori** [comment]
Made a few minor edits, looks good to me!

**Comment by mcourtot** [comment]
This was done in feb 2021, https://github.com/EBISPOT/DUO/blob/master/Governance2021.md
