### ISSUE TITLE
Change POA to a modifier term prohibiting POA research

### ISSUE THREAD

**Issue by solideoglori** [EBISPOT/DUO#54]
The proposal from Vivian at NIH/NCI is to make POA a MODIFER that can be applied to all data use categories of GRU, HMB, and DS.  

As with other modifers such as IRB Approval Required, Publication Required, Collaboration Required (which should be rare), Genetic Studies Only, POA should be added to these modifiers that could be possibly applied to GRU, HMB, and DS.

(For clarification based on prior communications that suggested otherwise, HMB still should be retained as a separate data use since it is not as broad as GRU since it’s uses are limited to health, medical, and biomedical uses.)

**Comment by solideoglori** [comment]
Such a change to the definition may look like...

Current: "This primary category consent code indicates that use of the data is limited to the study of population origins or ancestry."

Proposed: "This DUO term indicates use for purposes of population, origin, or ancesty research is prohibited."

Adrian asked if such a change may also warrant the change of the abbreviation from POA to NPOA.

**Comment by lymanrodriguez** [comment]
If a dataset is approved for GRU, why would population or ancestry research not be appropriate as a type of research?  I agree with this as a modifier for HMB or DS, so only question the GRU relevance.  I think it is helpful to have a fully unbounded research use term as it creates a clear "extreme" for understanding the spectrum of possibilities.

**Comment by mcourtot** [comment]
Just a point of process: If I read @solideoglori's (and Vivian + Adrian) proposal correctly above, this would imply completely changing the meaning of the term. If this is so, and to abide with our principle that meaning of the terms do not change through time, we would create a new term (new ID) for this and could decide whether we want to deprecate POA to prevent confusion.

**Comment by mcourtot** [comment]
Proposal agreed on the call:
- 3 main categories HMB, GRU and DS. 
- we should create an NPOA modifier
- we should not deprecate the POA main category as Sanger has specific datasets needing that restriction.

**Comment by mcourtot** [comment]
NPOA, DUO_0000044
