### ISSUE TITLE
Commercial access and use DUO code

### ISSUE THREAD

**Issue by HClissold** [EBISPOT/DUO#55]
It is unclear whether DUO:0000018 (Not-for-profit use only) is restricting use by commercial companies or restricting against commercial use. At Sanger, for most of our datasets, we allow access by commercial companies for research use only, but not commercial use. 

May I suggest separating these two things out. For example:
Label: Non-commercial **use** only
Description: This requirement indicates that use is limited to non-commercial research only (e.g. can be used by commercial organisations for research purposes, but not commercial purposes). 

Label: Non-commercial **access** only
Description: This requirement indicates that use is limited to non-commercial organisations.

**Comment by mcourtot** [comment]
H3Africa had similar feedback and requirements. Maybe Mamana or Nicky can comment. It'd be good to have a solution for a variety of use cases.

**Comment by mcourtot** [comment]
Is there a resolution for this?

**Comment by mcourtot** [comment]
DUO_0000018 label updated to encompass both as per definition, not for profit, non commercial use only

**Comment by mcourtot** [comment]
created NCU, DUO_0000046 and NPU, DUO_0000045
