### ISSUE TITLE
New Term Request: Clinical Use

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#59]
Per the H3Africa feedback, a new Clinical Use term is requested.

> This data use category indicates that use is allowed for clinical use and care.

@mamanambiya @nmulder can we get a proposed definition for "Clinical Care"?

**Comment by mamanambiya** [comment]
Proposed definition: 
**Clinical Care**: Health care or services provided at home, in a healthcare facility or hospital. Data may be used for clinical decision making.

**Comment by mcourtot** [comment]
Thanks @mamanambiya - this is not super explicit (eg what is a health care or service?) but may be good enough for a start. 

I expect the part "Data may be used for clinical decision making." is to be added to the clinical use term requested rather than the definition of clinical care?

**Comment by mcourtot** [comment]
example from Nicky; anything embedded in clinical making decision tool.

Resolution:
- create a term for clinical use (in DUO or somewhere else)
- create a new term clinical care use as sibling of general research use (see also #45)

**Comment by mcourtot** [comment]
done, DUO_0000043
