### ISSUE TITLE
New Term Request: Disease-specific Clinical use

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#60]
Request new term: disease-specific clinical use (e.g HIV only).  per H3Africa feedback

> This data use category indicates that use is allowed for clinical use and care of a specific disease (e.g. HIV only).

@mamanambiya would you please provide a use case?

**Comment by mamanambiya** [comment]
I would say a use case is when dataset can be used to inform clinical decision making, or in this case clinical decision making of a specific disease? I'm just wondering if this term is needed ie how frequently do we get cases where data can directly be applied to clinical decision making.

**Comment by mcourtot** [comment]
if needed, could it be 'built' by using 'clinical use' and 'disease specific' together?

**Comment by mcourtot** [comment]
Not needed at this point.
