### ISSUE TITLE
New Term Request: Drug Development Use

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#63]
New term: drug development use.

Per the feedback from H3Africa:
>  This data use category indicates that use is allowed for commercial drug development

Per Lyndon
> In some of our H3Africa consent forms, participants to agree to drug/diagnostic development.

@mamanambiya can you give an example of what the wording might be in the consent form?

**Comment by mamanambiya** [comment]
In some of our H3Africa consent forms, participants agree to drug/diagnostic development. This is a specific examples of commercial use so could be merged into commercial use with extended definition.

Example of text in consent forms:

> There is a small chance that your data, together with the data of many other people, could be used to develop new drugs or vaccines. If this happens, there are no plans to share any profit with you.”

**Comment by mcourtot** [comment]
Covered under commercial use #62
