### ISSUE TITLE
New Term Request: Diagnostic Test Development Use

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#64]
New term: Diagnostic test development use.

Per the H3Africa feedback:
> This data use category indicates that use is allowed for commercial diagnostic test development.

@mamanambiya would you be able to provide some example text from your consent forms where this is used?

**Comment by mamanambiya** [comment]
This is a specific examples of commercial use so could be merged into commercial use with extended definition.
We didn't find a specific example of this, and we may have added to be comprehensive, the following could be a start: 
> "The data and samples from you will not be sold. It is possible that researchers may develop commercially valuable products based on studying the data or samples, and if they do, you will not be able to share in any profits."

**Comment by mcourtot** [comment]
Covered under commercial use #62
