### ISSUE TITLE
New Terms Requested: Institution types

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#68]
Three new terms requested: Research Institution, commercial company, and not for profit company restrictions.  These would indicate that they are NOT allowed for use by these types.

Per H3Africa feedback

> These were created because the organization restriction seemed can be all encompassing, whereas these provide specific restrictions for different types of organisations. More specific.  For "research institution restriction" (for example) "This requirement indicates that data use is not allowed for use by research institutions."

Per @mcourtot 

> do we have use cases for those? We had purposely merged non-for-profit and commercial for example, as we found it hard to distinguish. For example, Broad is not for profit, but has commercial activities eg with CRISPR. What about an academic in partnership with a pharma company?

@mamanambiya  could you provide a bit more info based on the above?

**Comment by mcourtot** [comment]
Not needed at the moment
