### ISSUE TITLE
Term Change Request: General Research Use

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#70]
Term Change Request both name and definition: "General Research Use" to "Research Use"

Per H3Africa Feedback:

> Original:
> This primary category consent code indicates that use is allowed for general research use for any research purpose.
> 
> Changed:
> This data use category indicates that data use is allowed for research purposes.

@mamanambiya can you give more insight into how this would be used in your system?  Is there a concept of allowing "any research purpose"?

**Comment by mamanambiya** [comment]
This was originally proposed for use in an alternative structure that we proposed, but in the current structure, this is not necessary.

**Comment by mcourtot** [comment]
thanks for the feedback, closing this ticket.
