### ISSUE TITLE
CSV Update Request

### ISSUE THREAD

**Issue by calkinsh** [EBISPOT/DUO#77]
I may be overlooking something but the csv at the highest level of this repo (duo.csv) appears to be missing the entire class "investigation" which IS included in the stable release version shown at https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.owl.  I can see the investigation class in the csv under the directory src/ontology but i'm hesitant to use that since thats the "editors version".  Is it possible to regenerate the csv existing at the higher level to reflect the contents of the most recent stable release?  This is a really useful reference document for us in our implementation when working with people who are not comfortable viewing xml.

**Comment by mcourtot** [comment]
hi @calkinsh - thanks for the feedback. There is actually a ticket open to remove those from the display all together, https://github.com/EBISPOT/DUO/issues/52, as they're not meant to be used to indicate data use limitations and others have found it confusing to show them. 

Would you mind explaining a little bit more as to how you'd want to use those classes, and we can try and think of a way to accommodate the different use cases?

**Comment by calkinsh** [comment]
oh, thank you for pointing that out!  In fact I think we were going to use them incorrectly.  We had assumed these were ways to indicate limits for reuse only for specific types of research, though the fact that they are not a subclass of "data use limitation" should probably have tipped us off that this was incorrect.  

We are not yet fully implementing DUO, so we aren't actually using the investigation classes for anything "official" at this time, but we had noticed this discrepancy between the classes we were loading into our schema and the csv we were using to communicate with one of the data privacy analysts who reviews legal documentation before we ingest contributed data sets.  That's why I brought this up! 

We can remove these from our process, but I am just curious what their expected use is?

**Comment by mcourtot** [comment]
we were planning to use those as descriptors of datasets - so the data use limitation is on a datasets that is about a specific type of investigation.

Given that you are the second person confused by this I am wondering if we wouldn't be better off deprecating them. I'll raise this with the group, thanks again for the feedback and prompt response!

**Comment by calkinsh** [comment]
That makes sense! Thank you!  We are going to remove them from our system as we already have numerous other fields used to describe the data itself, but I am very interested to hear what you all decide!

**Comment by mcourtot** [comment]
Created a new issue suggesting this - closing this ticket now. Thanks!
