### ISSUE TITLE
Disease Ontology Choices

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#79]
Per @ogishima at GEM Japan:
"As for Disease Specific Research Use (DUO:0000007), the guidance tries to extend the machine-readability of the disease-specific term by referring to other ontologies. To specify a disease classification using a disease ontology is very good idea. But we must be cautious about which disease classification and ontology we recommend to use. 

The International Classification of Disease (ICD) has been developed by the WHO countries with tremendous efforts, and the ICD is the international standard for disease classification. In Japan, under the leadership of the Ministry of Health, Labour and Welfare, we use the ICD term as the standard disease term. Every hospital uses the ICD terms, and captured disease names for research use are also in the ICD terms. We strongly recommend you to have enough discussion for choosing disease classification."

Per @mcourtot :
"In writing the recommendation, we aimed at finding the right balance between a guidance to would facilitate and promote data sharing and the goal of having its implementation be machine readable. This means that for popular cases such as disease specific restriction we were aiming at being a bit more prescriptive in terms of which resources to use to ease the burden of mapping between different implementations.

In trying to find a suitable ontology, we looked at the Disease ontology, Snomed, ICD etc, but obvioulsy each of these would be limited to their own system. On the other hand, Mondo has cross references to ICD, see for example https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004992 and attached screenshot. It even seems to have mappings to both ICD9 and 10, as well as DO, NCIT and Snomed amongst others.

Would that be suitable for your use case?"

Per @ogishima 
"I understand MONDO is a very useful and practical ontology for disease concept, on the other hand, in Japan, at this moment the Ministry of Health promotes the use of ICD, and MONDO is rarely used. Anyway, thank you for your consideration for revision of this guideline."

FYI: @cmungall @mellybelly

**Comment by monicacecilia** [comment]
At the kind request from @mcourtot, I prepared a document (many moons ago) with a few details about the benefits of using Mondo in this context, adding a little about existing collaborations/alignment with other resources (x-refs). This document can be found [here](https://docs.google.com/document/d/1xiqB3F8t-2kG2bP61PKDUm-_gPyMVDQdIu__X6JwrrE/). As requested, I've also added details on the DUO-Guidelines document.

Briefly, Mondo integrates knowledge from heterogeneous sources such as the National Cancer Institute Thesaurus (NCIt), the Online Mendelian Inheritance in Man (OMIM), SNOMED CT, ICD, ICD-O, OncoTree, MedGen, Disease Ontology, Experimental Factor Ontology, etc. (a complete list of ontologies used as sources, or for x-refs and alignment, can be found [here](https://mondo.monarchinitiative.org/pages/sources/)), paying special attention to tracking provenance in how it generates mappings between them, and yielding a logically coherent structure that unifies multiple disease resources. You can learn more about Mondo at https://mondo.monarchinitiative.org/, and by reaching out to us. We will be delighted to assist in any way we can with implementing Mondo as part of DUO's ```Disease Specific Research Use (DUO:0000007)```.

@mcourtot - I am so sorry about the prolonged silence. 🌺

**Comment by linikujp** [comment]
By seeing multiple examples, my suggestion is as below:

You may need to give users a flexibility to choose their preferred terminology. Different community has different preference depends on their specific application engineering. Is the MONDO's mapping accurate and complete?  Does it fit community's need?
And please do not ignore the effort of terminology mapping is done by OHDSI community.

What disease ontology to use is a long standing confusion for the community of ontology developers. We may need to conduct an evaluation or survey about this. 

For DUO, you may only need to point to a top level term of disease. Could there be a creative idea to accommodate communities' need?

**Comment by mellybelly** [comment]
Hi all, I propose DUO recommend a set of specific, open terminologies. While it is true that ICD10 is broadly used worldwide, it still lacks many rare diseases and cancer types. Mondo has reconciled many rare disease definitions, and NCIt has the most extensive cancer classification. I would therefore recommend Mondo, ICD10/11, HPO, and NCIt. HPO may be needed for specific phenotypes where there is no diagnosis/disease.

Also, HPO and Mondo are being added to OHDSI (and there are already mappings) and HL7 terminology collections, just FYI.

**Comment by mcourtot** [comment]
Thansk @linikujp and @mellybelly for the feedback. It may be useful to reiterate the goal of DUO, which is to provide a minimal set of data access conditions for general usage. While I do agree with the intent from @linikujp's comment, we aim at offering a recommendation for straightforward machine readability, and as indicated by @mellybelly, this is best done by recommending a specific set of resources. 
Note that recommending usage of specific resources does not preclude usage of others; indeed many ontologies are available, and some users may not be able to use the recommended ones. In those cases, we recommend using mapping tools. The [EMBL-EBI Ontology cross reference service OxO](https://www.npmjs.com/package/elixir-jsonschema-validator) is a good example of such mapping tool. 

_Summary: DUO recommends a set of terminologies to be used,  which provide the basis for automated evaluation. When non-recommended resources are being used, this may require an extra mapping step to leverage automated matching algorithms._

**Comment by mcourtot** [comment]
Hi @solideoglori - assigning that one for you to include as part of the documentation. It'd be good to review the current documentation in light of the changes we are making, and possibly streamline and update it as Moran and I wrote it a little while back.

**Comment by mcourtot** [comment]
@solideoglori is copying over the doc at https://docs.google.com/document/d/1xiqB3F8t-2kG2bP61PKDUm-_gPyMVDQdIu__X6JwrrE/edit to our GH repo.
Updates in the OWL file done to point to MONDO:0000001
